### ISSUE TITLE
Remove `declarative` library

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#1006]
### Description

We have introduced the `declarative` pkg since it was planned to reuse this pkg in each Kyma Module operator. Plans now have changed and this pkg already has been moved to the internal section. Let's remove this pkg and refactor the manifest reconciler to the operator pattern instead declarative.

### Reasons

- Easier to read and debug manifest reconciler
- Easier to implement new features for manifest reconciler
- `declarative` pkg is not a pkg which should be reused outside of KLM

### Acceptance Criteria

- [ ] Remove declarative pkg
- [ ] Refactor manifest reconciler to have the same behaviour as before
- [ ] Adapt test suits incl. unit- and integration-tests
