### ISSUE TITLE
Watcher: Stress Test

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#1047]
### Description

To know the limits of our current Watcher setup, we need to to a stress-test. The goal is to break the setup and thus know our current limits. We will have follow-up issues to implements certain features such an Istio rate-limiter and an exponential retry mechanism for the runtime watcher, but this should not be covered in this issue.

Points of failure which should be put under a stress-test:
- Istio Gateway + VirtualService
- Lifecyclemanager Server

An initial stress-test setup should look like the following:
- Local two cluster k3d setup, make sure to give your Docker Demon enough resources to have a smoth running KCP simulation
   - Use e2e test pipelines as inspiration how to setup everything on your machine (deploy clusters, install istio & cert-manager, use watcher_local_test make target)
   - Adjust KLM resources to match the same as on `prod` landscapes
- Write as small Go program which uses the certificate, deployed by the KLM on your SKR cluster, to send Watcher Events to the Istio Gateway
    - Request should be send in a very high frequence
    - Check response status of each request; if not 200 Istio Gateway threshold is reached
    - Check watcher metrics of KLM
        - Number of received events should be equal to number of successfully send requests
-  Document your finding about our thresholds and performance

The code of the test should be put under `tests/stress-test`.

### Reasons

The Watcher setup has not been checked how it performs under high load - Thus, we should know our current thresholds and document it down for future improvements.

### Acceptance Criteria

- [ ] Write a program which executes a Watcher stress-test
    - [ ] Should be easy to maintain
    - [ ] Store in KLM repo under `tests/<...>`
    - [ ] Create make target to run stress-test on k3d setup
- [ ] Runs Watcher stress-test locally
- [ ] Document your findings about performance and thresholds
- [ ] Create follow-up issues
    - [ ] Introduce ratelimiter for Istio Gateway if possible (please investigate on that topic)
    - [ ] Exponential retry mechanism in runtime-watcher
    - [ ] Stress-Test pipeline 
        - Pipeline which can be manual triggered or runs once a month
        - Should execute stress-test according to your findings
