### ISSUE TITLE
MVP: Infrastructure Operators

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/lifecycle-manager#12]
**Description**

The Infrastructure Operators are essential components in the [new reconciler architecture](https://github.com/kyma-project/kyma/issues/13759). They are following the [K8s operator pattern](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) reacting to data changes (defined in CRs).

The Infrastructure Operators will be responsible for the lifecycle management of managed Kubernetes clusters (SKR clusters) and their underlying network setup.

**Acceptance criteria**
- [ ] Create dedicated repositories for infrastructure operators' code base in the `kyma-project` organisation
- [x] CRDs are the data schema of CR resources and build the contract between the Provisioner Operator and other KCP components. The requirements of the infrastructure operators (especially in regards to the `Cluster` CRDs or how `kubeconfig` data are stored) are defined and aligned with other KCP components (e.g. KEB).
    - [x] `Cluster` CRD is created: https://github.com/kyma-incubator/reconciler/issues/1047
- [ ] The operators have to react on `Cluster` CRs and, depending on the resource change,
     - [ ] create/update/delete network configurations used by the Gardener cluster
     - [ ] create/update/delete Kubernetes clusters by interacting with Gardener
- [ ] Store/update the `kubeconfig` of a created Kubernetes cluster in a dedicated resource (e.g. 'Secret` resource)
- [ ] Operational requirements are covered
     - [ ] Exposing analysis and statistic-relevant data via Prometheus endpoint
     - [ ] Logging of critical events
     - [ ] Auditlog is integrated
     - [ ] Operational test was executed and trouble-shooting guides were created
- [ ] Documentation of the architectural design
- [ ] Security threat-modelling passed
- [ ] Microdelivery process established
- [ ] Load test executed and thresholds / limitations are identified

**Issues**
https://github.com/kyma-project/kyma/issues/13759

**Appendix**
* CRD = Custom Resource Definition
* CR = Custom Resource
* BYOC = Bring your own cluster
* SKR = SAP Kyma Runtime

**Comment by janmedrek** [comment]
Related: https://github.com/kyma-project/control-plane/issues/1952
