### ISSUE TITLE
Move module creation and signing logic from the CLI

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#1274]
### Description

Scripts/commands for preparing modules, scaffolding, building templates and signing/verifying them should not be a part of the end-user CLI. There should be a collection of such tools (perhaps a separate CLI?) in a separate repository.

- create the repository scaffold
- copy specific commands with their tests

Related tickets to consider:

- https://github.com/kyma-project/cli/issues/1941

### Reasons

We want a setup oriented toward the module developers, not both them and the end-users of Kyma.

### Acceptance Criteria

- [x] #1305
  - Release pipeline/process set-up 
- [ ] Implement module commands
  - https://github.com/kyma-project/modulectl/issues/9
  - https://github.com/kyma-project/modulectl/issues/10
- [x] #1307

To Consider:
- [ ] Documentation generation set up (keep the documentation in the repository)
- [ ] Deprecation of commands in KymaCLI, after they have been covered in new Module CLI

**Comment by janmedrek** [comment]
As a note: it may be worth keeping the CLI intact as there may be some dependencies coming from other teams.

I believe we should just copy and adapt the logic from the CLI and save it as mini-CLI or bunch of scripts in the LM repository

**Comment by ruanxin** [comment]
The signing logic not make too much sense introduce to modulectl, but rather use  [OCM CLI](https://github.com/open-component-model/ocm?tab=readme-ov-file#ocm-cli) since it's a native feature offered by it. There is also a very [comprehensive guide](https://ocm.software/docs/getting-started/getting-started-with-ocm/sign-component-versions/) available, which even supports creating key pairs.

Benefits of using the OCM CLI:

- It is a well-documented tool.
- It is the official component in the OCM ecosystem for building and shipping OCM components.
- The verification part is done by the supported team in the restricted market, right? So third parties can also share this tool, and we don't need to handle the delivery of modulectl to them.
- It will reduce the maintenance efforts and complexity for modulectl.
