### ISSUE TITLE
Lifecycle Manager delivery

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/lifecycle-manager#13]
**Description**
The Lifecycle Manager is an essential component in the[ new reconciler architecture](https://github.com/kyma-project/kyma/issues/13759). It is following the [K8s operator pattern](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) reacting on data changes (defined in CRs).

The Lifecycle manager is responsible for the lifecycle management of _Kyma installations_ (respectively the components configured for a Kyma cluster) and determining the Kyma installation status (aka. cluster status).

**Acceptance criteria**
- [x] #77 
- [x] #78
- [x] #49
- [x] Documentation of the architectural design
- [ ] Operational requirements are covered
     - [ ] #79
     - [x] Exposing analysis and statistic relevant data via Prometheus endpoint
     - [x] Logging of critical events
     - [x] Auditlog is integrated
     - [ ] Operational test was executed and trouble-shooting guides were created
- [ ] Threat modelling findings implemented (see https://github.com/kyma-project/lifecycle-manager/issues/144)
    - [ ] https://github.com/kyma-project/lifecycle-manager/issues/13
    - [x] https://github.com/kyma-project/lifecycle-manager/issues/146
- [ ] Microdelivery process established

**Issues**
https://github.com/kyma-project/kyma/issues/13759

**Appendix**
* CRD = Customt Resource Definition
* CR = Custom Resource
* BYOC = Bring your own cluster
* SKR = SAP Kyma Runtime

**Comment by janmedrek** [comment]
Documentation was recently merged and includes all the architectural and user documentation.
Regarding the audit logs - all the operations are executed via the K8S API server, which is already accounted for in the audit logging configuration.
