### ISSUE TITLE
No-Downtime CA Certificate Rotation

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/lifecycle-manager#1430]
### Description

In https://github.com/kyma-project/lifecycle-manager/issues/1428 it was decided to implement a No-Downtime solution for our CA-Certificate which is used in our PKI for the runtime-watcher.

This approach involves a two-phase migration of clients, allowing for a slow, gradual transition with zero downtime. In the table below, you can see the detailed steps of the procedure when the CA-Certificate gets rotated. 'rootA+rootB' signifies that the CA-certificates have been concatenated and set as the 'ca.crt' value in the certificate secret. When transitioning from 'rootA+rootB' to 'rootB', it entails truncating the CA-Certificate String and removing the first certificate from the concatenation.

Detailed description of how the procedure looks like

| Step | Step-Name                 | Gateway Server Cert | Gateway Accepts Clients (CACert on KCP) | Clients Accepts Server (CACert on SKR) | Client Cert | Note                                          |
|------|---------------------------|---------------------|-------------------------|------------------------|-------------|-------------------------------------------------|
| 01   | Initial setup             | rootA               | rootA                   | rootA                  | rootA       | ""                                              |
| 02   | Generate rootB cert in KCP| rootA               | rootA                   | rootA                  | rootA       | ""                                              |
| 03   | Reconfigure the Gateway in the KCP| rootA        | rootA+rootB             | rootA                  | rootA       | All clients with the old Certificates signed by rootA still work |
| 04   | Migrate Clients to Certificates signed by rootB| rootA| rootA+rootB       | rootA+rootB            | rootB       | ""                                              |
| 05   | After alle Clients are migrated, switch Gate to accept only certs signed by rootB| rootB| rootB               | rootB                  | rootB       | ""                                              |

For this procedure we need to introduce a new process which takes care of this stateful process. We should evaluate the following ideas:
- Have a Go routine running in the KLM
- Have a new reconciler, reconciling CA Certificates, in the KLM
- Cron Job running in the KCP
- Sidecar attached to KLM (could also include tiny reconciler, reconciling over CA Certificates)
- **TBD**

Depending on the implementation details, we also need to find a proper way for monitoring this process, as well as testing it. In addition after this solution has been implemented and tested, we should delete the  temporary solution, implemented with https://github.com/kyma-project/lifecycle-manager/issues/1061, to shorten the reconciliation time again.

### Reasons

Please have a look at the following issues:
- https://github.com/kyma-project/lifecycle-manager/issues/1428
- https://github.com/kyma-project/lifecycle-manager/issues/1061
- https://github.com/kyma-project/lifecycle-manager/issues/1073

### Acceptance Criteria

- [ ] Implement new process to cover No-Downtime CA Certification rotation
- [ ] Cover new process in unit as well as with E2E Tests
- [ ] Come up with a proper monitoring solution
    - [ ] Implement needed metrics
    - [ ] Cover new metrics with a corresponding dashboard
    - [ ] Think about creating alert rules

### Feature Testing

End-to-End tests

## Implementation Hints

The Gardener project had a very similar problem and them have a written proposal how it was implemented. Since we decided to also go for a CA-Bundle solution, we can have a look at their proposal and implementation: https://github.com/gardener/gardener/blob/master/docs/proposals/18-shoot-CA-rotation.md
