### ISSUE TITLE
Performance Test for new reconciler architecture

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/lifecycle-manager#15]
For the longterm, a regular performance check of the reconciliation product is required. The load test should be executed periodically / per release as part of the CI/CD.

Goal is gain information how the general performance of the product evolves. The statistics should give an indication whether the general product performance has in- or decreased between releases.

AC:
### Concept
- [ ] Define Performance Test Concept
- [ ] Align concept with team

### Implementation
- [ ] Implement the load test scenario
    - #18
    - [ ] Boostrap test infrastructure (e.g. create new cluster or use hibernation in Gardener to stop/start landscapes)
    - [ ] Run load test scenarios
    - [ ] Shutdown test infrastructure
        - [ ] Delete generated test resource
        - [ ] Teardown test infrastructure (remove generated resources, stop test infrastructur)
- [ ] Show results in Grafana dashboard and make these data available in the longterm (enables us to compare how to performance profile evolves over time)
- [ ] [Setup CI/CD pipeline which executes the load test regularly (at least once per week and per new release)](https://github.com/kyma-project/lifecycle-manager/issues/359)

**Comment by pbochynski** [comment]
Please have a look at this work: https://github.com/pbochynski/kymactl#performance-test
Maybe you can use some ideas.

**Comment by ruanxin** [comment]
Hi @pbochynski, thanks for your performance test repo! many insights, especially the Findings part.

What I did until now is basically try to verify and setup some periodical prow job to run load test with different scenarios. I prepared a [presentation slides](https://sap-my.sharepoint.com/:p:/p/xin_ruan/EQ0YPwurAJVCkR8T9agjY0ABvTlgs0kM1iUlKpJuR6rADg?e=mpfisa) which plan to introduce last week, maybe you can also have a look (it's already presented within jellyfish team). 
General idea:
- use a load testing tool k6 as load generator, rely on some build-in thresholds as client side performance indicators, e.g: request duration time.
- config alert thresholds for some KPI metrics with grafana alertmanager
- pulling alert status with grafana api during tests, treat it as server side performance indicators, e.g: controller metrics
- verify all thresholds as pass/fail criteria which is native supported by k6

A poc demo can be find here: https://github.com/ruanxin/performance-test

Since I have one week vocation, this task I handover to @Tomasz-Smelcerz-SAP now, and will continue after I'm back.

**Comment by Tomasz-Smelcerz-SAP** [comment]
Remote reconciliation strategy: https://github.com/kyma-project/kyma-operator/issues/30

**Comment by janmedrek** [comment]
Closing in favor of https://github.com/kyma-project/lifecycle-manager/issues/359
