### ISSUE TITLE
Create monitoring for the new Reconciler Ecosystem

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/lifecycle-manager#292]
**Description**

We need to configure proper monitoring and alerting rules for the new reconciler architecture.

The Jellyfish team has to expose the metrics, configure the alert rules and handover all the resources which SREs should monitor.

**Acceptance Criteria:**
- [ ] Monitoring for relevant resources/fields is created
  - Performance-related metrics are exposed by the LM and MM
  - Controller Runtime metrics are exposed
- [ ] Monitoring for Kyma sync status https://github.com/kyma-project/lifecycle-manager/issues/380
- [x] Monitoring for when the Kyma CRs are in the error state for too long (time aggregation) https://github.com/kyma-project/lifecycle-manager/issues/381
  - The threshold should be set up later
  - Should not be tied to the performance
  - Alert rule set up when the threshold is there
- [x] Audit Policies in Gardener
- [ ] Alert rules for the KCP set-up (management-plane-config) https://github.com/kyma-project/lifecycle-manager/issues/382
  - Set up thresholds for the monitored values 
- [ ] Handover to SREs

**Follow-ups:**
- [ ] SKR Monitoring for Watcher or set up monitoring to check whether Kyma CR is synced

**Comment by janmedrek** [comment]
Lifecycle Manager monitors whether the connection to the SKR is up, if it breaks it will put up appropriate info in the Kyma CR in the KCP. Thus, we would only need to monitor the resources in the KCP (as all the changes and errors will be propagated there).
