### ISSUE TITLE
Documentation rework for reconciler ecosystem

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#420]
**Description**

In order to provide an in-depth look into the new Modularization approach and enable users to begin their journey with quick-start scenarios and examples, we would need a proper documentation structure set up in the repository.

The suggested structure is:
- [x] (Lifecycle Manager README.md) #423
- [x] (Lifecycle Manager /docs/user/quick-start) #424
- [x] (Lifecycle Manager /docs/user/tutorials) #425
- [x] (Lifecycle Manager /docs/developer) #426
- [x] (Lifecycle Manager /docs/module-development) #427
