### ISSUE TITLE
Release process and delivery pipelines for new reconciler ecosystem

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/lifecycle-manager#43]
**Description**

The new reconciler product consists of multiple different services and resources (e.g. Kyma operator, Manifest operators, Kyma CRDs etc.). The creation of release and the lifecycle management of the different components of this product can be challenging (especially in regards to configuration options and updates). A concept is required, how all resources have to be deployed and properly configured in Kubernetes to get the product working (potential solutions could be to the HELM package manager, Kyma CLI etc.).

Additionally, a lightweight end2end test is required to verify that the the new reconciler product was successfully installed and is ready to work.

Finally, SREs have to be ramped up and enabled to implement a delivery pipeline in their CI/CD system (Spinnaker) to automate the rollout and update of the new reconciler product to the KCP DEV/ STAGE / PROD landscapes.

AC:
- [x] Define a concept how the lifecycle of the reconciler will be managed / how the release process works 
    - [x] Concept is aligned within the team and SREs
- [ ] Necessary tooling for the lifecycle management is configured / implemented (e.g. [CLI command](https://github.com/kyma-project/cli/issues/1318) etc.)
- [x] SREs are ramped up and [tooling is passed over so that SREs](https://github.com/kyma-project/lifecycle-manager/issues/183) can configure their CI/CD system to deliver the new reconciler product to KCP landscapes
- [ ] Simple E2E test case is implemented to verify the correct deployment of the reconciler product
- [x] ~End-user documentation (main audience is SRE and developer) is available~ -> see https://github.com/kyma-project/community/issues/700

**Reason**
Establish a solution for lifecycle management of the new reconciler ecosystem.

**Comment by tobiscr** [comment]
Depends on parts of https://github.com/kyma-project/cli/issues/1325

**Comment by jakobmoellersap** [comment]
My suggestion:

- [ ] Create a hook / pipeline to parse the images build in the post-build jobs (e.g. `post-main-lifecycle-manager-build`)
- [ ] Take that image and parse it with Kustomize plus Overlays per Environment and use that image from the job in the `IMG` variable: for a reference, look at https://github.com/kyma-project/lifecycle-manager/blob/main/operator/Makefile#L98-L101 but we should parse the kustomize into a repository instead and use it from ArgoCD or another GitOps system. This Git Repo will need to be updated with the new images (ideally automatically without a Bump PR)
- [ ] Deploy to Environment with apply

**Comment by jakobmoellersap** [comment]
Also Quick Note: we do not want to use Spinnaker any longer (discussed in last sync)

**Comment by tobiscr** [comment]
Relates to [internal SRE issue](https://github.tools.sap/kyma/backlog/issues/2887).

**Comment by janmedrek** [comment]
Covered by [internal SRE ticket](https://github.tools.sap/kyma/backlog/issues/3499) and by the #187
