### ISSUE TITLE
Documentation improvements for Lifecycle Manager

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#550]
**Description**

The documentation for Lifecycle Manager needs to be improved so that it is more transparent and guides the user through the whole component and Module contribution journey.

**Acceptance Criteria**

- [x] The documentation includes an overview of Lifecycle Manager and its architecture.
- [x] The documentation provides a clear explanation of the different components of Lifecycle Manager.
- [ ] The documentation includes a step-by-step guide for contributing a new Module to Lifecycle Manager.
- [x] The documentation provides examples and use cases to illustrate the functionality of Lifecycle Manager.
- [ ] The documentation describes the channel concept.
- [ ] The documentation is up-to-date with the latest changes and features of Lifecycle Manager.

**Reasons**

Lifecycle Manager is a key component of Kyma, and it is important that users have a clear understanding of how to use it and contribute to it. Improving the documentation will make it easier for users to get started with Lifecycle Manager and reduce the number of support requests and improve the overall user experience.

**Attachments**

N/A

**Comment by mmitoraj** [comment]
We can think about the order of the developer tutorials - from basic to more complex ones. Tutorials' titles could also be changed to imperatives to describe their goal more precisely.
