### ISSUE TITLE
Enable the Runtime Watcher by default

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#649]
**Description**

Right now the reconciliation for the Runtimes is only time-based. Enabling the [Watcher](https://github.com/kyma-project/runtime-watcher) component will allow us to increase the reconciliation loop time, improve the performance and make it more comfortable for the users as all the changes will be picked up faster.

**Acceptance Criteria**

- [x] https://github.com/kyma-project/lifecycle-manager/issues/288
- [x] https://github.com/kyma-project/lifecycle-manager/issues/521
- [x] https://github.com/kyma-project/lifecycle-manager/issues/853
- [x] https://github.com/kyma-project/runtime-watcher/issues/63
- [x] https://github.com/kyma-project/runtime-watcher/issues/100

**Reasons**

We want to go with a better, more-performant setup.
