### ISSUE TITLE
Modularization API Upgrade

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/lifecycle-manager#776]
**Description**

With the features requested the current API of the modularization components is getting outdated, we need to upgrade it to ensure that we can continue to provide support and new features to our users.

**Acceptance Criteria**

- [x] https://github.com/kyma-project/lifecycle-manager/issues/543
- [x] https://github.com/kyma-project/lifecycle-manager/issues/196
- [x] https://github.com/kyma-project/lifecycle-manager/issues/296
- [x] https://github.com/kyma-project/lifecycle-manager/issues/890
- [ ] https://github.com/kyma-project/lifecycle-manager/issues/1075
- [x] https://github.com/kyma-project/lifecycle-manager/issues/913
- [x] https://github.com/kyma-project/lifecycle-manager/issues/1477
- [x] https://github.com/kyma-project/lifecycle-manager/issues/1247
- [ ] https://github.com/kyma-project/lifecycle-manager/issues/1709
- [x] https://github.com/kyma-project/lifecycle-manager/issues/1839
- [ ] https://github.com/kyma-project/lifecycle-manager/issues/1769
- [ ] consider if this should be included: https://github.com/kyma-project/lifecycle-manager/issues/1711
- [ ] Rollout plan for the upgrade made
- [ ] Documentation for the API adjusted

Consider and discuss: https://github.com/kyma-project/lifecycle-manager/issues/2235#issuecomment-2671444244

**Reasons**

Upgrading the API version of the Lifecycle Manager operator is necessary to ensure that we can continue to provide support and new features to our users. Upgrading the API version will bring many benefits, including better stability, performance, and functionality. 

**Attachments**

**Comment by jeremyharisch** [comment]
The field `kyma.spec.modules[i].controllername` is not used and deprecated. It should be fully removed on next API release.

**Comment by ruanxin** [comment]
# Change optional to required
- `manifest.spec.version`
- `moduletemplate.spec.mandatory`

# Remove
- `manifest.spec.config`
- `kyma.spec.modules[i].controllername`

**Comment by janmedrek** [comment]
As the discussions started recently - we should revisit how ModuleTemplates are used:
- how can we change/simplify ModuleTemplate CRD?
- is there something we can drop?
- ModuleTemplates should be used specifically for the KLM, not as a source of information for other components/UI
- Perhaps we can drop them and use the same stuff as the UI? It would require using some sort of central module registry

**Comment by TorstenD-SAP** [comment]
@janmedrek I would not drop the module template at all since it is basically an OCM descriptor. OCM is already part of the North Star Architecture document and will soon be part of the Product Security Standard (there are already discussions ongoing). In addition it will be used in some automation around Vulnerability Management by SGS to identify the owners of container images (an initiative towards that goal is already ongoing). The removal of the corresponding CRD should be no problem.

**Comment by janmedrek** [comment]
We should not use the stored image version migrator as it is not compatible with GKE clusters (and introduces a massive amount of errors).

> If the new version involves schema changes and requires custom logic, a conversion webhook should be implemented in KLM.
If there are no schema changes, the default None conversion strategy may be used in the CRD. Then I would just proceed with the "Option 2: Manually upgrade the existing objects to a new stored version" as [documented in the K8S docs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#upgrade-existing-objects-to-a-new-stored-version), i.e. to have a simple script which  list all existing related objects and write them with the same content. This forces the backend to write objects in the current storage version. Then moduify the KLM chart to drop the old version in the CRD status.storedVersions (edited)
