### ISSUE TITLE
Acceptance tests coverage metric

### ISSUE THREAD

**Issue by ameteiko** [kyma-project/lifecycle-manager#860]
**Description**

Implement a metric to measure the added acceptance tests coverage for each delivered feature.

**Subtasks:**

- [x] Create a PoC for a features coverage metric
- [x] Create a filter for feature commits
- [x] Conteinerise the metric calculator into a Docker image
  - [x] Upload image to the DockerHub
  - [x] Refine the metric invocation API
- [x] Build a report for calculated metrics

**Acceptance Criteria:**

- [x] The metric provides data:
    - [x] the number of delivered features
    - [x] the number of altered test scenarios
    - [x] the trend for an E2E coverage

**Comment by ameteiko** [comment]
The metric reporter in the [github.tools.sap/pandas/coverage-metrics](https://github.tools.sap/pandas/coverage-metrics) repository.

**Comment by ameteiko** [comment]
Follow the quality trend: https://wiki.one.int.sap/wiki/display/kyma/Quality+Trend
