### ISSUE TITLE
Refine the E2E scenarios to become Acceptance Criteria

### ISSUE THREAD

**Issue by ameteiko** [kyma-project/lifecycle-manager#925]
To reach the Functional Completeness quality standard, exposing the current E2E testable surface as a list of human-readable auditable acceptance criteria is essential.

## Tasks
 - [x] Refine the existing testing scenario descriptions:
     - [x] Kyma deletion
     - [x] Kyma status metric upon SKR cluster deletion
     - [x] Status propagation
     - [x] Watcher test
 - [x] Refactor the existing test suites with the refined ACs #938
 - [x] Compose a dictionary for the [ubiquitous language](https://martinfowler.com/bliki/UbiquitousLanguage.html)
 - [x] Align the dictionary with a domain expert
 - [x] Incorporate a coverage report generation into a GitHub Action
 - [ ] Present the results to the team

## Acceptance Criteria
 - [x] The auditable AC report is generated for the testing surface.
 - [x] The E2E testing scenarios refinement is proposed.

**Comment by ameteiko** [comment]
The refined ACs for the E2E test suite

[AC.pdf](https://github.com/kyma-project/lifecycle-manager/files/12829409/AC.pdf)

**Comment by ameteiko** [comment]
The report with highlighted keywords. The list of keywords comes from the remote Wiki URL.

![Image](https://github.com/kyma-project/lifecycle-manager/assets/1386964/3a149440-e866-4d10-929c-950a010702a1)
