### ISSUE TITLE
Unit testing improvements

### ISSUE THREAD

**Issue by ameteiko** [kyma-project/lifecycle-manager#972]
### Description

Refine the unit-testing infrastructure and prepare it for measuring the testing quality. 

### Subtasks

**Coverage**

- [x] Define a unit-testing coverage quality gate to ensure it does not degrade for critical packages.
- [ ] Generate a comprehensive coverage report
- [x] Explore possibilities for introducing the SonarCube 

**Code restructuring**

- [ ] Isolate domain-critical codebase that must be tested from one with lower coverage expectations.
- [x] Split unit test suite from the integration test suite (env tests)

**CI/CD**

- [x] Create a GH Action quality gate for a unit testing quality
- [x]  Add a ratcheting quality mechanism for the unit testing quality

**Strategy**

- [ ] Define the expectations on the unit-test coverage for the critical internal packages
